### ISSUE TITLE
Use of `glob(**)` in top-level BUILD.bazel breaks builds in dirty workspaces

### ISSUE THREAD

**Issue by jmillikin-stripe** [google/containerregistry#11]
(copied/moved from https://github.com/google/subpar/issues/29)

`BUILD.bazel` contains this target:

```
py_library(
   name = "containerregistry",
   srcs = glob(["**/*.py"]),
   deps = [ ... ]   
)
```

In a clean workspace, that glob picks up only the intended Python sources. But the build creates `bazel-*` symlinks, which are then detected by the glob and break later builds:

```console
$ bazel clean
$ bazel build :pusher.par
INFO: Found 1 target...
Target //:pusher.par up-to-date:
  bazel-bin/pusher.par
INFO: Elapsed time: 1.992s, Critical Path: 0.54s
$ bazel build :pusher.par
INFO: Found 1 target...
ERROR: /Users/jmillikin/src/containerregistry/BUILD.bazel:36:1: Building par file //:pusher.par failed: I/O exception during sandboxed execution: /private/var/tmp/_bazel_jmillikin/165d82f9b8e48612b4a588f395fdde11/execroot/containerregistry/bazel-bin (No such file or directory).
Target //:pusher.par failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.503s, Critical Path: 0.06s
```

This can be fixed by using a more verbose glob over the directories you expect to exist:

```python
py_library(
   name = "containerregistry",
   srcs = glob([
     "__init__.py",
     "client/**/*.py",
     "tools/**/*.py",
     "transform/**/*.py",
     "transport/**/*.py",
   ]), 
```

Another solution is to move the `containerregistry` target to a subdir, so it won't pick up stray build artifacts.

**Comment by mattmoor** [comment]
We could probably add `exclude=["bazel-*/**/*.py"]` to the `glob`, but I'll go for the slightly less lazy enumeration you suggest.  thanks again for spotting this.

**Comment by duggelz** [comment]
Can you also file a bug against Bazel itself?  It's supposed to have logic to ignore these links for globbing, I believe.

**Comment by mattmoor** [comment]
Yeah, I will open one.
