### ISSUE TITLE
fast_pusher is racy

### ISSUE THREAD

**Issue by ensonic** [google/containerregistry#115]
The biggest source of flakyness in our ci build (using bazel) is fast_pusher running into this:

```
F1016 05:27:50.844152   15925 fast_pusher_.py:186] Error publishing eu.gcr.io/my-project/my-image:daily-2018-10-16-2c53248c: Error fetching credential for gcloud, exit status: 1
ERROR: gcloud crashed (OperationalError): database is locked

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
```

As a workaround we've tried to add
```
docker-credential-gcloud get https://eu.gcr.io
```
to make sure we refreshed credentials before running a series of parallel push commands, but this is not sufficient :/

Any ideas?

**Comment by dekkagaijin** [comment]
Not sure, I'm guessing that there's contention between `gcloud` invocations to generate access tokens. There isn't much to `docker-credential-gcloud` or `gcloud auth docker-helper` itself.

@ensonic the command you'd want is `echo -n "https://eu.gcr.io" | docker-credential-gcloud get`

**Comment by ensonic** [comment]
@dekkagaijin: sorry escaping issues with markdown: the command we run is
```
docker-credential-gcloud get <<<https://eu.gcr.io
```

**Comment by dekkagaijin** [comment]
This'd be a good issue to post internally for the gcloud sdk team, since I'm guessing that the cause is in a common path. iirc there's a component for the docker helpers. I wouldn't call this a google/containerregistry bug, since it most likely affects a whole bunch of tools that'd use docker-credential-gcloud

**Comment by justinsb** [comment]
I think this is going through https://github.com/GoogleCloudPlatform/docker-credential-gcr; I wonder if forcing the auth-refresh is not helping when we concurrently push a dozen or so images: https://github.com/GoogleCloudPlatform/docker-credential-gcr/blob/7e55abeb1839689afa77070b523e0057a5c961cd/credhelper/helper.go#L215

I think that means that "preloading" the credentials is also ineffective.

Perhaps we would do better to specify e.g.  `--min-expiry=300s`.  We might also benefit from a single retry there, for when the token expires - I'm not sure of the exact semantics.

Is this going through docker-credential-gcr?  Should I send a PR there?

**Comment by jonjohnsonjr** [comment]
I ran into something similar: https://github.com/GoogleCloudPlatform/docker-credential-gcr/issues/54

**Comment by jonjohnsonjr** [comment]
This got fixed internally recently (in gcloud). Anecdotally, all my tools are now ~4x faster because getting access tokens from gcloud is _much_ faster. Going to close this, please reopen if you still see it after updating gcloud.
