### ISSUE TITLE
Cache downloaded layers

### ISSUE THREAD

**Issue by anchlovi** [google/containerregistry#120]
Currently we are using bazel over GCB and we have a performance issue with `rules_docker` where images are downloaded on every invocation

We would like to solve this issue by introducing a cache mechanism to `containerregistery` puller. Downloaded layers will be stored and fetched from this cache. The cache will be by layer so different images will be able to reuse layers that were already downloaded from different images

**Comment by mattmoor** [comment]
It sounds like Bazel distributed caching would be even more useful to you.  Have you looked into it at all?

cc @nlopezgi

**Comment by ittaiz** [comment]
Thanks @matmoor for your reply.
I think you’re incorrect. Bazel remote caching is for actions but unfortunately Bazel needs to have all of the external repositories on disk even if they exist in the remote CAS.
This is why Bazel has the repository_cache feature (currently only for files downloaded via the standard Bazel mechanism).
On Dev machines this is a net win.
On CI with ephemeral workers (like google’s GCB) you can use a GCP CDN and still get much faster results.

FTR we also use RBE (remote execution by google)
