### ISSUE TITLE
fast_puller_.py pulls an image with an unknown SHA256 from quay.io

### ISSUE THREAD

**Issue by alex1545** [google/containerregistry#148]
I'm using the fast puller to pull an image from quay.io, but according to the SHA256 in the digest file, it pulls some other image.

All of the following calls yield the same result, where the SHA256 of the image being pulled is `sha256:955b57c68705a57290f6e34b00e40ee7ec33e0138d39bf0b8759f7a2f709e70b`:

```
$ python puller.par --name quay.io/coreos/kube-state-metrics:v1.5.0 --directory .
$ python puller.par --name quay.io/coreos/kube-state-metrics:latest --directory .
$ python puller.par --name quay.io/coreos/kube-state-metrics@sha256:b7a3143bd1eb7130759c9259073b9f239d0eeda09f5210f1cd31f1a530599ea1 --directory .
$ python puller.par --name quay.io/coreos/kube-state-metrics@sha256:f686e2b6c67d4eeee782eada446a1720ae14e7ade8fc4e4e254844262affd7fa --directory .
```

When trying to pull the image specifying the SHA256 of the image that was actually pulled, like so:
```
$ python puller.par --name quay.io/coreos/kube-state-metrics@sha256:955b57c68705a57290f6e34b00e40ee7ec33e0138d39bf0b8759f7a2f709e70b --directory .
```
I'm getting the following error:
```
F0401 19:17:02.952016  171301 __main__.py:147] Error pulling and saving image quay.io/coreos/kube-state-metrics@sha256:955b57c68705a57290f6e34b00e40ee7ec33e0138d39bf0b8759f7a2f709e70b: response: {'status': '404', 'content-length': '82', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Mon, 01 Apr 2019 23:17:02 GMT', 'content-type': 'application/json'}
manifest unknown: {}
```

**Comment by jonjohnsonjr** [comment]
The fast puller is up-converting the image from the ancient manifest v2 schema 1 format to the more modern manifest v2 schema 2 format. That up-conversion necessarily changes the digest of the manifest, so trying to pull it from quay will not succeed. Quay hasn't upgraded all repositories to support schema 2 images yet (from what I've been told by them, there's a migration currently in progress), but once they do you should see stable digests.
