### ISSUE TITLE
Doens't work with Bazel 0.25.0 because it uses Python 3 by default

### ISSUE THREAD

**Issue by Monnoroch** [google/containerregistry#153]
Either need to support Python 3 or set `python_version = "PY2"` for all python binaries.

**Comment by KaylaNguyen** [comment]
We'll roll out our update for Python3 compatibility soon.

**Comment by Monnoroch** [comment]
Thanks, Kayla! Still, it's not fixed yet, so maybe we shouldn't close the bug until it is.

**Comment by pcj** [comment]
I believe you can also do 

```
build --incompatible_py3_is_default=false
# maybe or maybe not in conjunction with 
build --incompatible_allow_python_version_transitions=false
```

**Comment by Monnoroch** [comment]
@pcj yeah, that'll do as a temp solution, but it would still be more correct to specify a python version for each binary.

**Comment by endobson** [comment]
Any update on an ETA for this?

**Comment by fejta** [comment]
This is still problematic

**Comment by prestonvanloon** [comment]
Any update?
