### ISSUE TITLE
container_pull authentication failure

### ISSUE THREAD

**Issue by echupriyanov** [google/containerregistry#38]
I'm having an issue with `container_pull` from private Docker Registry based on Sonatype OSS Nexus Repository Manager:
```
containerregistry.client.v2_2.docker_http_.BadStateException: Unexpected "www-authenticate" challenge type: BASIC
 (/usr/bin/python /private/var/tmp/_bazel_eric/35e4f788de46e2946a456376a62aa566/external/puller/file/puller.par --directory /private/var/tmp/_bazel_eric/35e4f788de46e2946a456376a62aa566/external/base/image --name suxen.vipdmp.com/com.veon/jvm-builder@sha256:e3aefc80adf5c8d403a1887d55f53c54ded0cdaf3b1c3e95bb861526b9cb515f).
```

Looking at Python source code, I see, that it only accepts `Basic` challenge type and not `BASIC`
I suppose the check should be case-insensitive.

**Comment by KingEmet** [comment]
Ack, have a CR in flight internally. Sick profile photo.

Looks like the spec requires case insensitivity:
https://tools.ietf.org/html/rfc2617#section-1.2

**Comment by KingEmet** [comment]
Case-insensitivity is retained in the updated spec:
https://tools.ietf.org/html/rfc7235#section-2.1
