### ISSUE TITLE
Ping failures should have clearer error messages.

### ISSUE THREAD

**Issue by mattmoor** [google/containerregistry#56]
If you have a simple typo in your registry domain (e.g. `usr.gcr.io`) then you'll get a cryptic callstack ending in a failure to `self._Ping()`.

Given that the error message doesn't even print the domain, you basically need an expert to understand why this might be failing.

**Comment by mattmoor** [comment]
@dekkagaijin @jonjohnsonjr Any takers? :)

**Comment by dekkagaijin** [comment]
Roger
