### ISSUE TITLE
flatten isn't published for v0.0.26

### ISSUE THREAD

**Issue by promiseofcake** [google/containerregistry#79]
In an effort to use published artifacts (to fix an issue with @six dependencies for [rules_docker](https://github.com/bazelbuild/rules_docker/blob/master/container/container.bzl#L41-L47)), `flatten.par` has not been published.

`https://storage.googleapis.com/containerregistry-releases/<release>/flatten.par` is missing.

Is this expected? There are published artifacts available for:

* appender.par
* puller.par
* pusher.par
* importer.par

This would allow `rules_docker` to use the published artifacts, and not require all of the dependencies for `containerregistry` to be available to rules_docker and to the parent WORKSPACE.

**Comment by jonjohnsonjr** [comment]
Whoops - fixed :)

**Comment by promiseofcake** [comment]
Thanks so much @jonjohnsonjr!
